digital_device: # 开关量
  addr: 1 # 站号
  input: # 读输入离散量 02
    swtich1: 1 # 起始地址
    swtich2: 2
    swtich3: 3
  output: # 读/写输出线圈 01/05
    motor_h1: 1
    motor_h2: 2
    motor_l1: 3
    motor_l2: 4
    lock: 5

analog_device: # 模拟量
  addr: 2
  input:
    force: 1 # 读入寄存器 04

rfid_device: # 只接收没有主动读
  addr: 3